import React, { useState } from 'react';
import { AssessmentResult, TrustAssessmentState } from '../types';

interface EnhancedAssessmentResult extends AssessmentResult {
  confidence?: string;
  improvement_actions?: Array<{
    category: string;
    suggestion: string;
    impact: string;
  }>;
  re_evaluation_hint?: string;
  agent_insights?: {
    purpose_routing?: any;
    data_interpretation?: any;
    trust_reasoning?: any;
    bias_fairness?: any;
    improvement_guidance?: any;
  };
}

interface Props {
  result: EnhancedAssessmentResult;
  state: TrustAssessmentState;
}

const EnhancedTrustProfile: React.FC<Props> = ({ result, state }) => {
  const [showDetails, setShowDetails] = useState(false);
  const [activeTab, setActiveTab] = useState('summary');

  const getBandColor = (band: string) => {
    if (band.startsWith('T5')) return 'text-emerald-600 bg-emerald-50 border-emerald-200';
    if (band.startsWith('T4')) return 'text-blue-600 bg-blue-50 border-blue-200';
    if (band.startsWith('T3')) return 'text-indigo-600 bg-indigo-50 border-indigo-200';
    if (band.startsWith('T2')) return 'text-amber-600 bg-amber-50 border-amber-200';
    return 'text-rose-600 bg-rose-50 border-rose-200';
  };

  const getConfidenceColor = (confidence: string) => {
    if (confidence === 'high') return 'text-green-600 bg-green-50';
    if (confidence === 'moderate') return 'text-yellow-600 bg-yellow-50';
    return 'text-red-600 bg-red-50';
  };

  return (
    <div className="space-y-8 animate-in zoom-in duration-700">
      <div className="text-center space-y-2">
        <h3 className="text-xl font-bold text-slate-900">AI-Powered Trust Assessment</h3>
        <p className="text-xs text-slate-500 uppercase tracking-wider font-semibold">
          Generated by 5 specialized AI agents
        </p>
      </div>

      {/* Main Result */}
      <div className={`p-8 rounded-[2rem] border-2 text-center space-y-4 ${getBandColor(result.trustBand)}`}>
        <div className="text-5xl md:text-6xl font-black tracking-tighter">
          {result.trustBand.split(' ')[0]}
        </div>
        <div className="text-xl font-bold">
          {result.trustBand.split(' - ')[1]}
        </div>
        
        {/* Confidence Badge */}
        {result.confidence && (
          <div className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-bold ${getConfidenceColor(result.confidence)}`}>
            <span className="w-2 h-2 rounded-full bg-current mr-2"></span>
            {result.confidence.toUpperCase()} CONFIDENCE
          </div>
        )}
        
        <div className="h-px bg-current opacity-20 w-16 mx-auto"></div>
        <p className="text-sm font-medium leading-relaxed max-w-sm mx-auto">
          {result.interpretation}
        </p>
      </div>

      {/* Navigation Tabs */}
      <div className="flex bg-slate-100 rounded-xl p-1">
        <button
          onClick={() => setActiveTab('summary')}
          className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-colors ${
            activeTab === 'summary' 
              ? 'bg-white text-slate-900 shadow-sm' 
              : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          Summary
        </button>
        <button
          onClick={() => setActiveTab('reasoning')}
          className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-colors ${
            activeTab === 'reasoning' 
              ? 'bg-white text-slate-900 shadow-sm' 
              : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          AI Reasoning
        </button>
        <button
          onClick={() => setActiveTab('guidance')}
          className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-colors ${
            activeTab === 'guidance' 
              ? 'bg-white text-slate-900 shadow-sm' 
              : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          Guidance
        </button>
      </div>

      {/* Tab Content */}
      {activeTab === 'summary' && (
        <div className="space-y-6">
          {/* Credit Alignment */}
          <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100 text-center space-y-1">
            <p className="text-xs text-slate-400 font-bold uppercase tracking-widest">Indicative Credit Alignment</p>
            <p className="text-xl font-bold text-slate-800">
              Typically associated with the <span className="text-indigo-600">{result.traditionalAlignment}</span> range
            </p>
            <p className="text-[10px] text-slate-400">This is not an official credit score and does not replace bureau scores.</p>
          </div>

          {/* Key Reasoning */}
          <div className="space-y-4">
            <h4 className="text-sm font-bold text-slate-900 uppercase tracking-wide">Key Analysis Points</h4>
            <div className="grid gap-3">
              {result.reasoning.map((item, i) => (
                <div key={i} className="flex items-start gap-3 p-4 bg-white rounded-xl border border-slate-100 shadow-sm">
                  <span className="mt-1 text-green-500">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>
                  </span>
                  <p className="text-sm text-slate-700">{item}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {activeTab === 'reasoning' && (
        <div className="space-y-6">
          {/* AI Agent Pipeline */}
          <div className="space-y-4">
            <h4 className="text-sm font-bold text-slate-900 uppercase tracking-wide">AI Agent Analysis Pipeline</h4>
            
            {/* Agent 1: Purpose Routing */}
            <div className="bg-white p-4 rounded-xl border border-slate-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                  <span className="text-blue-600 font-bold text-sm">1</span>
                </div>
                <div>
                  <h5 className="font-semibold text-slate-900">Purpose & Routing Agent</h5>
                  <p className="text-xs text-slate-500">Policy-based evaluation planning</p>
                </div>
              </div>
              {result.agent_insights?.purpose_routing && (
                <div className="text-sm text-slate-600 bg-slate-50 p-3 rounded-lg">
                  <p><strong>Purpose:</strong> {result.agent_insights.purpose_routing.plan?.purpose}</p>
                  <p><strong>Required Layers:</strong> {result.agent_insights.purpose_routing.plan?.required_layers?.join(', ')}</p>
                  <p><strong>Risk Tolerance:</strong> {result.agent_insights.purpose_routing.plan?.risk_tolerance}</p>
                </div>
              )}
            </div>

            {/* Agent 2: Data Interpretation */}
            <div className="bg-white p-4 rounded-xl border border-slate-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                  <span className="text-green-600 font-bold text-sm">2</span>
                </div>
                <div>
                  <h5 className="font-semibold text-slate-900">Data Interpretation Agent</h5>
                  <p className="text-xs text-slate-500">AI-powered pattern analysis</p>
                </div>
              </div>
              {result.agent_insights?.data_interpretation && (
                <div className="text-sm text-slate-600 bg-slate-50 p-3 rounded-lg">
                  <p><strong>Behavioral Coherence:</strong> {result.agent_insights.data_interpretation.signals?.behavioral_coherence}</p>
                  <p><strong>Evidence Quality:</strong> {result.agent_insights.data_interpretation.signals?.evidence_support_level}</p>
                  <p><strong>Coverage:</strong> {result.agent_insights.data_interpretation.signals?.evidence_coverage_months} months</p>
                </div>
              )}
            </div>

            {/* Agent 3: Trust Reasoning */}
            <div className="bg-white p-4 rounded-xl border border-slate-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center">
                  <span className="text-purple-600 font-bold text-sm">3</span>
                </div>
                <div>
                  <h5 className="font-semibold text-slate-900">Trust Reasoning Agent</h5>
                  <p className="text-xs text-slate-500">AI-powered trust decision making</p>
                </div>
              </div>
              {result.agent_insights?.trust_reasoning && (
                <div className="text-sm text-slate-600 bg-slate-50 p-3 rounded-lg">
                  <p><strong>Primary Basis:</strong> {result.agent_insights.trust_reasoning.decision?.primary_basis?.join(', ')}</p>
                  <p><strong>Modifiers:</strong> {result.agent_insights.trust_reasoning.decision?.secondary_modifiers?.join(', ')}</p>
                  {result.agent_insights.trust_reasoning.decision?.guardrails_applied?.length > 0 && (
                    <p><strong>Guardrails:</strong> {result.agent_insights.trust_reasoning.decision.guardrails_applied.join(', ')}</p>
                  )}
                </div>
              )}
            </div>

            {/* Agent 4: Bias & Fairness */}
            <div className="bg-white p-4 rounded-xl border border-slate-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-yellow-100 rounded-lg flex items-center justify-center">
                  <span className="text-yellow-600 font-bold text-sm">4</span>
                </div>
                <div>
                  <h5 className="font-semibold text-slate-900">Bias & Fairness Agent</h5>
                  <p className="text-xs text-slate-500">AI-powered fairness audit</p>
                </div>
              </div>
              {result.agent_insights?.bias_fairness && (
                <div className="text-sm text-slate-600 bg-slate-50 p-3 rounded-lg">
                  <p><strong>Fairness Checks:</strong> {result.agent_insights.bias_fairness.audit?.fairness_checks_passed ? '✅ Passed' : '⚠️ Adjustments Made'}</p>
                  {result.agent_insights.bias_fairness.audit?.adjustments_applied?.length > 0 && (
                    <p><strong>Protections Applied:</strong> {result.agent_insights.bias_fairness.audit.adjustments_applied.join(', ')}</p>
                  )}
                </div>
              )}
            </div>

            {/* Agent 5: Improvement Guidance */}
            <div className="bg-white p-4 rounded-xl border border-slate-100">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-indigo-100 rounded-lg flex items-center justify-center">
                  <span className="text-indigo-600 font-bold text-sm">5</span>
                </div>
                <div>
                  <h5 className="font-semibold text-slate-900">Improvement & Guidance Agent</h5>
                  <p className="text-xs text-slate-500">AI-powered personalized coaching</p>
                </div>
              </div>
              <div className="text-sm text-slate-600 bg-slate-50 p-3 rounded-lg">
                <p>Generated personalized improvement recommendations and user-friendly explanations</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'guidance' && (
        <div className="space-y-6">
          {/* Improvement Actions */}
          {result.improvement_actions && result.improvement_actions.length > 0 && (
            <div className="space-y-4">
              <h4 className="text-sm font-bold text-slate-900 uppercase tracking-wide">Personalized Improvement Actions</h4>
              <div className="grid gap-4">
                {result.improvement_actions.map((action, i) => (
                  <div key={i} className="bg-white p-4 rounded-xl border border-slate-100">
                    <div className="flex items-start gap-3">
                      <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                        <span className="text-blue-600 font-bold text-xs">{action.category.charAt(0)}</span>
                      </div>
                      <div className="flex-1">
                        <h5 className="font-semibold text-slate-900 mb-1">{action.category}</h5>
                        <p className="text-sm text-slate-700 mb-2">{action.suggestion}</p>
                        <p className="text-xs text-slate-500 italic">{action.impact}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Re-evaluation Hint */}
          {result.re_evaluation_hint && (
            <div className="bg-blue-50 p-6 rounded-2xl border border-blue-100">
              <h4 className="text-sm font-bold text-blue-900 mb-2">Future Opportunities</h4>
              <p className="text-sm text-blue-800">{result.re_evaluation_hint}</p>
            </div>
          )}
        </div>
      )}

      <div className="pt-6">
        <button 
          onClick={() => window.location.reload()}
          className="w-full py-4 text-slate-500 font-bold hover:text-slate-800 transition-colors"
        >
          Close Report
        </button>
      </div>
    </div>
  );
};

export default EnhancedTrustProfile;